//
//  StaticDataModel.swift
//  Notes
//
//  Created by Dmitry on 22.12.2022.
//

import Foundation

struct StaticDataModel {
    static let DataModelArray: [DataModel] = [DataModel(header: "Steve Jobs", textBody: "Steven Paul Jobs (February 24, 1955 – October 5, 2011) was an American entrepreneur, industrial designer, media proprietor, and investor. He was the co-founder, chairman, and CEO of Apple; the chairman and majority shareholder of Pixar; a member of The Walt Disney Company's board of directors following its acquisition of Pixar; and the founder, chairman, and CEO of NeXT. He is widely recognized as a pioneer of the personal computer revolution of the 1970s and 1980s, along with his early business partner and fellow Apple co-founder Steve Wozniak."),
                                              DataModel(header: "Elon Musk", textBody: "Elon Reeve Musk FRS (/ˈiːlɒn/ EE-lon; born June 28, 1971) is a business magnate and investor. He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter, Inc.; founder of The Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation. With an estimated net worth of around $164 billion as of December 13, 2022, primarily from his ownership stakes in Tesla and SpaceX, Musk is the second-wealthiest person in the world according to both the Bloomberg Billionaires Index and Forbes's real-time billionaires list."),
                                              DataModel(header: "Mark Zuckerberg", textBody: "Mark Elliot Zuckerberg (/ˈzʌkərbɜːrɡ/; born May 14, 1984) is an American business magnate, internet entrepreneur, and philanthropist. He is known for co-founding the social media website Facebook and its parent company Meta Platforms (formerly Facebook, Inc.), of which he is the chairman, chief executive officer, and controlling shareholder. Zuckerberg attended Harvard University, where he launched Facebook in February 2004 with his roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz, and Chris Hughes. Originally launched to select college campuses, the site expanded rapidly and eventually beyond colleges, reaching one billion users by 2012. Zuckerberg took the company public in May 2012 with majority shares. In 2007, at age 23, he became the world's youngest self-made billionaire. Since 2008, Time magazine has named Zuckerberg among the 100 most influential people in the world as a part of its Person of the Year award, which he was recognized with in 2010. In December 2016, Zuckerberg was ranked tenth on Forbes list of The World's Most Powerful People. In the Forbes 400 list of wealthiest Americans in 2022 he was ranked 11th with a wealth of $57.7 billion, down from his status as the third richest American in 2021 with a net worth of $134.5 billion. As of November 2022, Zuckerberg's net worth was $33.5 billion according to the Forbes Real Time Billionaires making him the 29th richest person in the world. On April 10 and 11, 2018, Zuckerberg testified before the United States Senate Committee on Commerce, Science, and Transportation regarding the usage of personal data by Facebook in relation to the Facebook–Cambridge Analytica data breach.")]
}
